#!/usr/bin/env sh
echo
echo "
\e[38;5;39m███████╗\e[0m \e[38;5;18m ██████╗ \e[0m
\e[38;5;39m██╔════╝\e[0m \e[38;5;18m██╔═══██╗\e[0m
\e[38;5;39m█████╗  \e[0m \e[38;5;18m██║   ██║\e[0m
\e[38;5;39m██╔══╝  \e[0m \e[38;5;18m██║   ██║\e[0m
\e[38;5;39m██║     \e[0m \e[38;5;18m╚██████╔╝\e[0m

Obrigado por contribuir! - Equipe From Zer0_
"